# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eb2db613a39c079ff969fb554cb66ce6bf8010d0ae59ba6d41d28abf4691745c691def1fcf758bff6b2473ac52919dcdc7f7727a42882be1b61e6936e1c9f94

test:
  secret_key_base: c0971262dcc2ebf76fb9b404fa110332623cf3643ba5d63a96b1e97d27944079b11f12656ddf54083d1792c92634bb82dd5c0e3baf4d6ff7c604c1d77ebcc622

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
